### PR TITLE
Bugfix: dispose issue

### PR DESCRIPTION
**Pull request by schillingdavid**
Fixed an issue with the disposing of the animation controller which could cause memory leaks and crashes

### CODE REVIEW

**Comment by schillingdavid** [comment]
Fixes the following exception:

The following assertion was thrown while finalizing the widget tree:
_FlutterPasswordStrengthState#61795(ticker active) was disposed with an active Ticker.

_FlutterPasswordStrengthState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

**Comment by arielt** [comment]
Checking back, I think it is still a useful fix.

**Comment by schillingdavid** [comment]
> Checking back, I think it is still a useful fix.

I'm quite sure the documentation even says not to use super.dispose() first but to use it at the very last.

**Comment by schillingdavid** [comment]
So first dispose children, and after that the parent, or there will be orphans.

**Pull request closed without merging**
