### PR TITLE
Bugfix: Dispose Issue

### PR DESCRIPTION
**Pull request by schillingdavid**
Fixed an issue with the disposing of the animation controller which could cause memory leaks and crashes.

### CODE REVIEW

**Comment by schillingdavid** [comment]
Fixes the following exception:

The following assertion was thrown while finalizing the widget tree:
_FlutterPasswordStrengthState#61795(ticker active) was disposed with an active Ticker.

_FlutterPasswordStrengthState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

**Comment by volmus** [comment]
Any news on this @JinHoSo ?

**Review by JinHoSo — APPROVED** [review]

**Comment by JinHoSo** [comment]
@schillingdavid Thank you 🙏

**Comment by schillingdavid** [comment]
> @schillingdavid Thank you 🙏

Of course! 😊 Do you plan on tagging a new release real soon? 😊 If so, what do you think when? 😬

**Comment by arielt** [comment]
Hi , looks like the fix was reverted in one of the later commits: d28089d64a3f4c92690c7220a061eb8167e1e0ab
Any chance to restore it? 
The issue with the Ticker is seen again.

**Comment by schillingdavid** [comment]
> Hi , looks like the fix was reverted in one of the later commits: [d28089d](https://github.com/JinHoSo/flutter-password-strength/commit/d28089d64a3f4c92690c7220a061eb8167e1e0ab) Any chance to restore it? The issue with the Ticker is seen again.

Yeah, it really was reverted. I added a new Pull Request #17.
It'll be merged after @JinHoSo  reviewed and accepted it. 😊

**Comment by arielt** [comment]
Checking back, I think it is still a useful fix.

**Comment by robyf** [comment]
Any news on this?

**Pull request merged**
